SUP-3054 removed refs to pcp, clean up distribute methods docs, added…
puppetlabs/ca_extend pull request #59
Opened 2022-03-18 17:03 UTC by taikaa

SUP-3054 

### Prior to this commit: 
It was not apparent to ca_extend users that they did not need to use ssh/winrm to distribute the CA certificate to agents, if the CA certificate has not yet expired. Additionally, the **Configuration** section did not make clear at which point in the process users make the decision to use an Inventory file, connect Bolt to Puppet DB, or use ~/.ssh/config. The README also made references to PCP transport without details on which tasks/plans are supported to run via PCP.

### This commit:
Adds an additional option for distributing a copy of CA cert to agents, using a Puppet `file` resource along with including an example of puppet code using this option. There is now a total of three suggested methods for distribution, and these methods are now logically located under the **Usage**. What was formerly the **Configuration** section has been logically relocated to the usage instructions for **1. Using the ca_extend::upload_ca_cert Plan** because the references to inventory files, transport configuration, and Puppet DB belongs here. Removes references to PCP transport because not all tasks/plans in `ca_extend` at this time support use via the Orchestrator.

2022-03-18 17:17 UTC, m0dular requested changes
Looks great, just a minor note about the `rm` example.

2022-03-21 13:26 UTC, taikaa commented
Which change should be made to the rm example? Remove -r or change something else? Thanks! @m0dular

2022-03-21 19:42 UTC, m0dular requested changes

2022-03-21 19:42 UTC, m0dular commented on README.md
> +rm -rf $(puppet config print localcacert)
Could we remove the `-rf` options?  We shouldn't need recursive or force for a regular file.

2022-03-21 20:08 UTC, m0dular approved these changes

2022-03-21 20:14 UTC, m0dular requested changes
Looks great, but could we change the commit message so the changelog will be a little more readable?  The format should generally be something like

```
(SUP-3054) README updates

This commit does x, y, and z.
```
Where the first line has the JIRA key in parenthesis followed by a brief description, then a newline followed by a paragraph with more specific details about the commit.

2022-03-21 20:15 UTC, m0dular commented
We should be able to change the commit message with `git commit --amend` followed by `git push -f`

2022-03-21 21:18 UTC, m0dular approved these changes

2022-03-21 21:19 UTC, merged